spring.application.name=BookTrack

# JWT Configuration
app.jwtSecret=mySecretKeyForBooktrackApplicationPleaseChangeThisInProductionWithALongerKeyForSecurity
app.jwtExpirationMs=86400000

# Server Configuration
server.port=8081
server.servlet.context-path=/
